---
- include: nginx-official-repo.yml
  when: nginx_official_repo == True
- include: installation.packages.yml
  when: nginx_installation_type == "packages"
- include: ensure-dirs.yml
- include: remove-defaults.yml
  when: not keep_only_specified
- include: remove-extras.yml
  when: keep_only_specified
- include: remove-unwanted.yml
- include: auth_basic.yml
- include: configuration.yml
- include: configuration-ent.yml
  with_dict: '{{ ent_sites }}'
  when: ent_sites is defined
- include: configuration-wordpress.yml
  with_dict: '{{ wordpress_sites }}'
  when: wordpress_sites is defined
- include: configuration-spip.yml
  with_dict: '{{ spip_sites }}'
  when: spip_sites is defined
- include: configuration-cdn.yml
  with_dict: '{{ cdn_sites }}'
  when: cdn_sites is defined
- include: reload.yml
- include: logrotate.yml
  when: nginx_logrotate
  tags: logrotate
